Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -62,9 +62,9 @@ jobs:
           chmod +x mihomo
           sudo mv mihomo /usr/local/bin/mihomo
 
-      - name: Check mihomo version
+      - name: Check mihomo install
         run: |
-          mihomo version || (echo "mihomo install failed" && exit 1)
+          mihomo convert-ruleset --help || (echo "mihomo install failed" && exit 1)
 
       - name: Convert .list to .mrs
         run: |
